### ISSUE TITLE
Investigate Crash

### ISSUE THREAD

**Issue by san983** [voxbone-workshop/click2vox-com#722]
```
» 21 Jul 2017 11:42:26.006 155 <190>1 2017-07-21T14:42:25.809132+00:00 app web.1 - - TypeError: Cannot read property 'generateDivHtmlCode' of null at successResponse (/app/routes/widget.js:131:34) at /app/routes/widget.js:179:24 at /app/node_modules/mongoose/lib/query.js:2839:18 at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28) at wrappedPromise.linkTransaction (/app/node_modules/newrelic/lib/instrumentation/promise.js:295:65) at wrappedPromise.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:184:28) at __NR_wrappedThenHandler (/app/node_modules/newrelic/lib/instrumentation/promise.js:471:26) at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:135:7) Context
```

**Comment by san983** [comment]
Related to a timeout in the mLab instance, will keep an eye on it. Closing for now
